"""empty message

Revision ID: 12c720d0b2f8
Revises: c1c66f9a3b1f
Create Date: 2022-10-07 14:50:42.359287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c720d0b2f8'
down_revision = 'c1c66f9a3b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('modified_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'modified_at')
    # ### end Alembic commands ###
