"""empty message

Revision ID: 4b42de41e486
Revises: 7716e2f81d1c
Create Date: 2022-10-07 16:01:14.550272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b42de41e486'
down_revision = '7716e2f81d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_details', sa.Column('payment_method', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'payment_details', 'payment_types', ['payment_method'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_details', type_='foreignkey')
    op.drop_column('payment_details', 'payment_method')
    # ### end Alembic commands ###
