"""empty message

Revision ID: 7716e2f81d1c
Revises: d1e2fc2e379c
Create Date: 2022-10-07 15:55:19.531372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7716e2f81d1c'
down_revision = 'd1e2fc2e379c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payment_types_ibfk_1', 'payment_types', type_='foreignkey')
    op.drop_column('payment_types', 'provider_id')
    op.drop_constraint('user_payment_methods_ibfk_2', 'user_payment_methods', type_='foreignkey')
    op.drop_column('user_payment_methods', 'provider_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_payment_methods', sa.Column('provider_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_payment_methods_ibfk_2', 'user_payment_methods', 'payment_providers', ['provider_id'], ['id'])
    op.add_column('payment_types', sa.Column('provider_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('payment_types_ibfk_1', 'payment_types', 'payment_providers', ['provider_id'], ['id'])
    # ### end Alembic commands ###
