"""empty message

Revision ID: c1c66f9a3b1f
Revises: 0fec968900a5
Create Date: 2022-10-07 14:49:46.657348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1c66f9a3b1f'
down_revision = '0fec968900a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'modified_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('modified_at', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
